export const MENU_VISIBLE = 'MENU_VISIBLE';
export const ADD_ID_IN_STORE = 'ADD_ID_IN_STORE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOCATION_ADD = 'LOCATION_ADD';
export const LOCATION_COORDINATES = 'LOCATION_COORDINATES';
export const ADD_TOKEN = 'ADD_TOKEN';
export const IDS_RECENTLY = 'IDS_RECENTLY';
export const IDS_ARR = 'IDS_ARR';
export const SEARCH_STRING = 'SEARCH_STRING';
export const SORT_BY = 'SORT_BY';
export const ACTIVE_LIVE = 'ACTIVE_LIVE';
export const ACTIVE_BUTTON_CONTAINER = 'ACTIVE_BUTTON_CONTAINER';
export const LIVE_VISIBLE = 'LIVE_VISIBLE';
export const VIEW_PROFILE = 'VIEW_PROFILE';
export const REVIEWS_INFO = 'REVIEWS_INFO';
export const REVIEWS_IMG = 'REVIEWS_IMG';
export const CHAT_WITH = 'CHAT_WITH';
export const LOCATION_ID = 'LOCATION_ID';
export const ACTIVE_BUTTON_CONTAINER_WORK = 'ACTIVE_BUTTON_CONTAINER_WORK';
export const SELECTED_BUTTON_CONTAINER = 'SELECTED_BUTTON_CONTAINER';
export const CHANGE_PROFILE_IMG = 'CHANGE_PROFILE_IMG';


